import {Practice} from './engine.mjs';
import {bindCardTap} from './touch.mjs';
const $=id=>document.getElementById(id), synth=window.speechSynthesis;
let game,cards=[],timer,watchdog,utterance,token=0,startedAt=0,roundHint=false,pausePhase=null,assetsReady=false;
const buttons=new Map;
let screen='opening',kind='practice',attack=null,clockInterval,rankRequest=0,rankOrigin='menu',profilePromise=null,runRequest=0;
const fmt=ms=>{const n=Math.max(0,Math.round(ms/100));return `${Math.floor(n/600)}:${String(Math.floor(n/10)%60).padStart(2,'0')}.${n%10}`};
function showScreen(next){screen=next;document.body.className='screen-'+next;for(const [id,visible]of Object.entries({opening:next==='opening',menu:next==='menu',setup:next==='game'&&game?.phase==='ready',reader:next==='game'&&game?.phase!=='ready',result:next==='result',boardWrap:next==='game',daily:next==='ranks'||next==='result'}))$(id).hidden=!visible;window.scrollTo({top:0,behavior:'instant'})}
function categoryNow(){return {count:Number(document.querySelector('input[name=count]:checked').value),speed:$('speed').value}}
async function requestAPI(path,body){if(path!=='/api/profile'){await(profilePromise??=requestAPI('/api/profile').catch(e=>{profilePromise=null;throw e}))}const controller=new AbortController;const timeout=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(path.replace('/api/','/api/kks/'),{method:body?'POST':'GET',credentials:'same-origin',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,signal:controller.signal});let d;try{d=await r.json()}catch{throw Error('ランキングに接続できませんでした。')}if(!r.ok)throw Error(d.error||'通信できませんでした。');return d}finally{clearTimeout(timeout)}}
function tick(){if(attack)$('attackClock').textContent=fmt((attack.elapsed??(performance.now()-attack.start))+game.mistakes*3000+game.hints*5000)}
function eventLog(type,id){if(attack&&!attack.completed)attack.events.push({type,...(id?{id}:{}),t:Math.round(performance.now()-attack.start)})}
function modeChanged(){kind=document.querySelector('input[name=kind]:checked').value;$('nameField').hidden=kind!=='attack';$('playMode').textContent=kind==='attack'?'タイムアタック開始':'札をならべる';$('modeDescription').textContent=kind==='attack'?'クリア時間＋お手つき1回につき3秒＋読み句表示1回につき5秒でランキング。休憩中も時計は進みます。音声が使える端末で挑戦してください。':'聞き直しや読み句のヒントを使いながら、自分のペースで練習できます。'}
function backToMenu(){runRequest++;clearWork();clearInterval(clockInterval);attack=null;$('attackClock').hidden=true;if(game)game.phase='ready';$('playMode').disabled=!assetsReady;showScreen('menu');modeChanged()}
function quitToTitle(){backToMenu();pausePhase=null;startedAt=0;showScreen('opening');$('enter').focus({preventScroll:true})}
async function playSelected(){if(!assetsReady)return;const seq=++runRequest;$('menuError').hidden=true;const {count,speed}=categoryNow();if(kind==='practice'){attack=null;prepare();showScreen('game');return}$('playMode').disabled=true;$('playMode').textContent='札をならべています…';try{const data=await requestAPI('/api/runs',{count,speed});if(seq!==runRequest)return;clearWork();game.reset(count);game.board=data.board.map(id=>cards.find(c=>c.id===id));game.queue=data.order.map(id=>cards.find(c=>c.id===id));attack={id:data.id,start:null,events:[],count,speed,eligible:true,completed:false,elapsed:null,result:null,error:null,saving:false};board();showScreen('game');$('attackClock').hidden=false;$('start').textContent='読み上げてタイムアタック開始'}catch(e){if(seq!==runRequest)return;$('menuError').textContent=e.message||'通信できませんでした。もういちどお試しください。';$('menuError').hidden=false}finally{if(seq===runRequest){$('playMode').disabled=false;modeChanged()}}}
function ownNameLink(name){const b=document.createElement('button');b.type='button';b.className='name-link';b.textContent=name;b.setAttribute('aria-label',`自分の名前「${name}」を変更`);b.onclick=()=>openNameEdit(name);return b}
function openNameEdit(name){$('editNameInput').value=name;$('editNameError').hidden=true;$('editNameDialog').showModal();$('editNameInput').focus();$('editNameInput').select()}
async function saveNameEdit(e){e.preventDefault();const name=$('editNameInput').value.trim();if(!name||[...name].length>12){$('editNameError').textContent='1〜12文字で入力してください。';$('editNameError').hidden=false;return}$('saveNameEdit').disabled=true;$('saveNameEdit').textContent='保存しています…';$('editNameError').hidden=true;try{const profile=await requestAPI('/api/profile',{name});profilePromise=Promise.resolve(profile);if(attack?.result?.leaderboard){const board=attack.result.leaderboard;if(board.mine)board.mine.name=profile.name;board.entries.forEach(row=>{if(row.isMe)row.name=profile.name})}$('editNameDialog').close();await loadRanks()}catch(err){$('editNameError').textContent=err.message||'保存できませんでした。もういちどお試しください。';$('editNameError').hidden=false}finally{$('saveNameEdit').disabled=false;$('saveNameEdit').textContent='保存する'}}
function renderRanks(data){$('rankDate').textContent=`${data.day.replaceAll('-',' / ')} · ${data.count}枚 · ${{'0.8':'ゆっくり','1':'ふつう','1.15':'はやめ'}[data.speed]} · ${data.total}人`;$('rankContent').replaceChildren();if(!data.entries.length){const p=document.createElement('p');p.className='rank-empty';p.textContent='今日の記録は、まだありません。最初の挑戦者になろう！';$('rankContent').append(p)}else{const table=document.createElement('table');table.className='rank-table';const head=document.createElement('thead'),tr=document.createElement('tr');for(const t of ['順位','なまえ','タイム']){const th=document.createElement('th');th.scope='col';th.textContent=t;tr.append(th)}head.append(tr);table.append(head);const tbody=document.createElement('tbody');for(const row of data.entries){const tr=document.createElement('tr');if(row.isMe)tr.className='is-me';const rank=document.createElement('td'),name=document.createElement('td'),score=document.createElement('td');rank.textContent=row.rank;score.textContent=fmt(row.score);if(row.isMe){name.append(ownNameLink(row.name));const me=document.createElement('span');me.className='self-label';me.textContent='あなた';name.append(me)}else name.textContent=row.name;tr.append(rank,name,score);tbody.append(tr)}table.append(tbody);$('rankContent').append(table)}$('myBest').hidden=!data.mine;$('myBest').replaceChildren();if(data.mine){$('myBest').append(ownNameLink(data.mine.name),document.createTextNode(` の今日のベスト：${data.mine.rank}位 / ${data.total}人　${fmt(data.mine.score)}`))}}
async function loadRanks(){const seq=++rankRequest;$('rankContent').textContent='ランキングを読み込んでいます…';$('myBest').hidden=true;try{const data=await requestAPI(`/api/leaderboard?count=${$('rankCount').value}&speed=${encodeURIComponent($('rankSpeed').value)}`);if(seq===rankRequest)renderRanks(data)}catch(e){if(seq===rankRequest){$('rankContent').textContent=e.message+' 「更新する」で再試行できます。';$('rankDate').textContent=''}}}
function setRankCategory(count,speed){$('rankCount').value=String(count);$('rankSpeed').value=String(speed)}
function openRanks(){rankOrigin=screen;const c=categoryNow();setRankCategory(c.count,c.speed);showScreen('ranks');loadRanks()}
function renderAttack(){if(!attack)return;$('finalTime').textContent=fmt(attack.result?.score??attack.elapsed+game.mistakes*3000+game.hints*5000);$('scoreBreakdown').textContent=`クリア ${fmt(attack.elapsed)} ＋ お手つき ${game.mistakes*3}秒 ＋ ヒント ${game.hints*5}秒`;$('retrySave').hidden=!attack.error||!attack.eligible;$('saveStatus').textContent=!attack.eligible?'音声を確認できなかったため、今回は練習記録です。ランキングには登録されません。':attack.saving?'記録を送っています…':attack.error?'記録を送れませんでした。下のボタンで再試行できます。':attack.result?(attack.result.isBest?'今日の自己ベスト！　':'記録しました。　')+`現在 ${attack.result.leaderboard.mine.rank}位 / ${attack.result.leaderboard.total}人`:'記録を準備しています…'}
async function saveAttack(){const run=attack;if(!run||run.saving||!run.eligible||run.result)return;run.saving=true;run.error=null;renderAttack();try{run.result=await requestAPI('/api/finish',{id:run.id,events:run.events,elapsedMs:run.elapsed});if(attack===run&&screen==='result'){setRankCategory(run.count,run.speed);rankRequest++;renderRanks(run.result.leaderboard)}}catch(e){run.error=e.message}finally{run.saving=false;if(attack===run)renderAttack()}}
function finishAttackClock(){if(!attack||attack.completed)return;attack.elapsed=Math.round(performance.now()-attack.start);attack.completed=true;clearInterval(clockInterval);tick();saveAttack()}
function resultOutgame(){showScreen('result');const c=categoryNow();$('resultMode').textContent=`${c.count}枚・${{'0.8':'ゆっくり','1':'ふつう','1.15':'はやめ'}[c.speed]} / ${attack?'タイムアタック':'じっくり練習'}`;$('attackResult').hidden=!attack;setRankCategory(c.count,c.speed);if(attack){renderAttack();if(attack.result){rankRequest++;renderRanks(attack.result.leaderboard)}else loadRanks()}else loadRanks()}

function stopSpeech(){token++;clearTimeout(watchdog);synth?.cancel();utterance=null}
function clearWork(){clearTimeout(timer);stopSpeech()}
function setMessage(t){$('message').textContent=t}
function update(){ $('progress').textContent=`${game.taken.size} / ${game.board.length}枚`;$('mistakes').textContent=`お手つき ${game.mistakes}`;for(const [id,b]of buttons){b.disabled=game.phase!=='asking'||game.taken.has(id);b.classList.toggle('taken',game.taken.has(id))} $('replay').disabled=!['asking','waiting'].includes(game.phase);$('hint').disabled=game.phase!=='asking'; }
function board(){buttons.clear();$('board').replaceChildren();$('board').classList.toggle('full',game.board.length>12);for(const c of game.board){const b=document.createElement('button');b.className='card';b.setAttribute('aria-label',`${c.id} の絵札`);const im=document.createElement('img');im.src=c.image;im.alt=`${c.id} の絵札`;im.draggable=false;b.append(im);bindCardTap(b,()=>pick(c.id));buttons.set(c.id,b);$('board').append(b)}update()}
function prepare(){clearWork();$('start').textContent='読み上げをはじめる';game.reset(Number(document.querySelector('input[name=count]:checked').value));$('setup').hidden=false;$('reader').hidden=true;$('result').hidden=true;$('boardNote').textContent='札の位置を覚えよう';$('audioNotice').hidden=true;pausePhase=null;board()}
function reveal(){if(!roundHint){game.hints++;roundHint=true;eventLog('hint');tick()}$('reading').textContent=game.current.kana.replaceAll('、','　');$('reading').hidden=false}
function speechFailure(){if(attack)attack.eligible=false;if(!['waiting','asking'].includes(game.phase))return;game.phase='asking';if(!startedAt)startedAt=performance.now();setMessage('音声が出ないときは「もういちど聞く」');$('audioNotice').textContent='音量を確認して、もういちど聞いてください。音声が使えない場合は「読み句を見る」で文字の練習ができます。';$('audioNotice').hidden=false;update()}
function speak(){if(!['waiting','asking'].includes(game.phase))return;stopSpeech();const mine=token;const hasSpeech=!!synth&&'SpeechSynthesisUtterance'in window;if(!hasSpeech){speechFailure();return}game.phase='asking';update();let speechStarted=false;setMessage('声を聞いて、札をさがそう');const u=new SpeechSynthesisUtterance(game.current.kana);utterance=u;u.lang='ja-JP';u.rate=Number($('speed').value);const voice=synth.getVoices().find(v=>/^ja(?:-|_)/i.test(v.lang));if(voice)u.voice=voice;u.onstart=()=>{if(mine!==token)return;speechStarted=true;clearTimeout(watchdog);game.phase='asking';if(!startedAt)startedAt=performance.now();$('audioNotice').hidden=true;setMessage('声を聞いて、札をさがそう');update()};u.onend=()=>{if(mine!==token)return;clearTimeout(watchdog);if(game.phase==='waiting'){game.phase='asking';startedAt=performance.now();update()}if(game.phase==='asking')setMessage('どの絵札かな？')};u.onerror=e=>{if(mine!==token||e.error==='interrupted'||e.error==='canceled')return;clearTimeout(watchdog);speechFailure()};watchdog=setTimeout(()=>{if(mine===token&&!speechStarted&&game.phase==='asking')speechFailure()},7000);synth.resume();synth.speak(u)}
function ask(){clearTimeout(timer);roundHint=false;startedAt=0;$('reading').hidden=true;$('next').hidden=true;$('pause').textContent='休む';game.phase='waiting';speak();$('boardNote').textContent=game.board.length>12?'下にも札があります。ならびは変わりません。':'正しい絵札をタップしよう'}
function pick(id){const status=game.pick(id);if(status==='ignored')return;eventLog('pick',id);if(status==='wrong'){setMessage('お手つき。もういちど、さがそう！');const b=buttons.get(id);b.classList.add('wrong');setTimeout(()=>b.classList.remove('wrong'),450);update();return}if(game.taken.size===game.board.length)finishAttackClock();game.times.push(startedAt?(performance.now()-startedAt)/1000:null);stopSpeech();setMessage('とれた！');$('reading').textContent=game.current.kana.replaceAll('、','　');$('reading').hidden=false;$('next').hidden=false;$('next').textContent=game.taken.size===game.board.length?'結果を見る':'つぎの札へ';update();timer=setTimeout(next,2000)}
function next(){clearTimeout(timer);if(!game.advance())return;if(game.phase==='done'){finish();return}ask()}
function finish(){clearWork();$('reader').hidden=true;$('result').hidden=false;$('boardNote').textContent='ぜんぶ、とれました';const times=game.times.filter(v=>v!==null);const avg=times.length?(times.reduce((s,v)=>s+v,0)/times.length).toFixed(1)+'秒':'—';$('stats').replaceChildren();for(const [value,label]of [[game.taken.size+'枚','とった札'],[game.mistakes+'回','お手つき'],[avg,'平均のとる時間']]){const d=document.createElement('div'),strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=value;span.textContent=label;d.append(strong,span);$('stats').append(d)}update();$('result').scrollIntoView({block:'start',behavior:'smooth'});resultOutgame()}
function pause(){if(!game||['ready','done'].includes(game.phase))return;if(game.phase==='paused'){const prev=pausePhase;pausePhase=null;$('pause').textContent='休む';if(prev==='feedback'){game.phase='feedback';next()}else{game.phase='waiting';startedAt=0;speak()}return}pausePhase=game.phase;clearWork();game.phase='paused';$('pause').textContent='再開する';$('next').hidden=true;$('reading').hidden=true;setMessage('ひと休み中');update()}
$('start').onclick=()=>{if(!assetsReady)return;if(attack){attack.start=performance.now();clearInterval(clockInterval);clockInterval=setInterval(tick,100);tick()}$('setup').hidden=true;$('reader').hidden=false;ask()};$('replay').onclick=speak;$('hint').onclick=reveal;$('next').onclick=next;$('pause').onclick=pause;$('quitGame').onclick=quitToTitle;$('again').onclick=()=>{backToMenu();playSelected()};document.querySelectorAll('input[name=count]').forEach(el=>el.onchange=()=>{if(game?.phase==='ready'&&screen==='game')prepare()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&game&&!['paused','ready','done'].includes(game.phase))pause()});window.addEventListener('pagehide',clearWork);synth?.getVoices();
async function init(){try{const r=await fetch('cards.json');if(!r.ok)throw Error();cards=await r.json();game=new Practice(cards);prepare();showScreen('opening');await Promise.all(cards.map(c=>new Promise((resolve,reject)=>{const i=new Image;i.onload=resolve;i.onerror=reject;i.src=c.image})));assetsReady=true;$('loadStatus').textContent='44枚の絵札を準備できました';$('start').disabled=false;$('playMode').disabled=false;if(!synth){$('loadStatus').textContent='この端末は音声非対応です。「読み句を見る」で練習できます。'}registerTools();(profilePromise??=requestAPI('/api/profile')).catch(()=>{profilePromise=null});}catch{$('loadStatus').textContent='札を読み込めませんでした。通信を確認してページを開きなおしてください。';$('menuError').textContent=$('loadStatus').textContent;$('menuError').hidden=false}}
function registerTools(){if(!document.modelContext?.registerTool)return;const ctrl=new AbortController;window.addEventListener('pagehide',()=>ctrl.abort(),{once:true});const opts={signal:ctrl.signal};for(const t of [{name:'get_karuta_practice_state',description:'Read practice progress and board card identifiers, without revealing the current answer.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({phase:game.phase,count:game.board.length,taken:game.taken.size,mistakes:game.mistakes,cards:game.board.map(c=>({id:c.id,taken:game.taken.has(c.id)}))})},{name:'take_karuta_card',description:'Tap one visible picture card during the listening practice. Wrong answers count as mistakes.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||typeof input.id!=='string'||!buttons.has(input.id))throw Error('Unknown card');if(game.phase!=='asking'||game.taken.has(input.id))throw Error('Card cannot be taken now');pick(input.id);return{phase:game.phase,taken:game.taken.size,mistakes:game.mistakes}}}]){try{Promise.resolve(document.modelContext.registerTool(t,opts)).catch(()=>{})}catch{}}}
$('menuSettings').append(document.querySelector('#setup .settings'));
$('enter').onclick=()=>showScreen('menu');$('playMode').onclick=playSelected;$('changeMode').onclick=backToMenu;$('openingRanks').onclick=openRanks;$('menuRanks').onclick=openRanks;$('ranksBack').onclick=()=>showScreen(rankOrigin==='opening'?'opening':'menu');$('refreshRanks').onclick=loadRanks;$('rankCount').onchange=loadRanks;$('rankSpeed').onchange=loadRanks;$('retrySave').onclick=saveAttack;document.querySelectorAll('input[name=kind]').forEach(x=>x.onchange=modeChanged);$('editNameForm').onsubmit=saveNameEdit;$('cancelNameEdit').onclick=()=>$('editNameDialog').close();modeChanged();init();
