import {POWERS,assertDeck} from './engine.mjs';
const $=id=>document.getElementById(id);
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const data=await fetch('./cards.json').then(r=>{if(!r.ok)throw Error('Card DB unavailable');return r.json()});
const ALL=data.cards;assertDeck(ALL);
const by=id=>ALL.find(x=>x.id===id), gear=c=>c?.kind==='gear';
let s=null,selected=null,pending=null;
function log(msg){s.log.unshift(msg);s.log=s.log.slice(0,7)}
function takeTop(){if(!s.deck.length){s.deck=shuffle(s.discard);s.discard=[];log('捨て札を混ぜ、山札を作り直しました')}return s.deck.shift()||null}
function danger(diff){if(diff>0&&s.shield){s.shield=false;log('まもりの効果で危険度上昇を防ぎました');return} s.danger=Math.max(0,s.danger+diff);if(s.danger>=7){s.phase='lost';log('危険度7。封災失敗！')}}
function addTo(p,c){if(!c)return;p.hand.push(c)}
function draw(p,depth=0){if(depth>12)return;let c=takeTop();if(!c)return;log((p.cpu?p.name:'あなた')+'が「'+c.name+'」を引きました');if(c.kind==='happening'){happening(c,p);s.discard.push(c)}else if(c.kind==='guardian'){if(!p.guardian || p.cpu&&p.guardian.used){if(p.guardian)s.discard.push(p.guardian.card);p.guardian={card:c,used:false};log(p.name+'の相棒が '+c.name+' に交代')}else if(!p.cpu&&p===s.players[0]){pending={kind:'guardian',card:c};log('新しいガーディアンに交換できます')}else s.discard.push(c)}else addTo(p,c)}
function hasEquipment(ids){return s.players.some(p=>p.hand.some(c=>ids.includes(c.id)))||Object.values(s.slots).some(c=>ids.includes(c.id)))}
function happening(c,p){const protect={E001:['I002'],E002:['I001'],E003:['I016'],E005:['I011'],E006:['I005','I007']};if(protect[c.id]&&hasEquipment(protect[c.id])){log('備えがあったため「'+c.name+'」を無効化');return}switch(c.id){case 'E001':case 'E002':case 'E006':danger(1);break;case 'E003':s.players[(s.turn+1)%s.players.length].noGear=true;break;case 'E005':s.players[(s.turn+1)%s.players.length].noTransfer=true;break;case 'E004':danger(-1);draw(s.players.find(x=>x.hand.length<5)||p);break;case 'E007':{let t=takeTop();if(t){if(gear(t))addTo(p,t);else{s.discard.push(t);danger(1)}}break}case 'E008':{const a=takeTop(),b=takeTop();if(a)s.deck.unshift(a);if(b)s.deck.unshift(b);danger(-1);break}}}
function setup(){const count=Number($('count').value);const monsters=ALL.filter(c=>c.kind==='monster');const gs=shuffle(ALL.filter(c=>c.kind==='guardian'));const players=Array.from({length:count},(_,i)=>({name:i?'CPU '+i:'あなた',cpu:i>0,hand:[],guardian:null,noGear:false,noTransfer:false}));
for(const p of players){let picks=gs.splice(0,2);p.guardian={card:picks[0],used:false};gs.push(picks[1]);}
const eligible=shuffle(ALL.filter(c=>c.kind==='gear'||c.kind==='action'));for(let k=0;k<3;k++)for(const p of players)p.hand.push(eligible.shift());
s={players,deck:shuffle([...eligible,...gs,...ALL.filter(c=>c.kind==='happening')]),discard:[],monsters,monster:0,danger:1,slots:{},turn:0,turns:0,phase:'playing',actions:1,drawn:false,shield:false,log:[],sealCount:0};
selected=null;pending=null;log('ゲーム開始！ 5属性をそろえて封災しよう。');render();turnStart()}
function turnStart(){if(!s||s.phase!=='playing')return;s.actions=1;s.drawn=true;const p=s.players[s.turn];log(p.name+'の手番');draw(p);if(!p.cpu&&pending){render();return}if(p.cpu){cpuTurn()}else render()}
function removeCard(p,c){const i=p.hand.findIndex(x=>x.id===c.id);if(i<0)throw Error('Hand mismatch');p.hand.splice(i,1)}
function gearPlay(p,c){if(p.noGear||s.slots[c.power])return false;removeCard(p,c);s.slots[c.power]=c;log(p.name+'が '+c.name+' を置きました');if(p.guardian?.card.id==='G001'&&!p.guardian.used){p.guardian.used=true;draw(p)}if(p.guardian?.card.id==='G010'&&!p.guardian.used&&c.power==='そなえる'){p.guardian.used=true;draw(s.players.find(x=>x!==p)||p)}return true}
function actionPlay(p,c){removeCard(p,c);s.discard.push(c);log(p.name+'が '+c.name+' を使用');switch(c.id){case 'A001':{if(s.players.length>1){const other=s.players.find(x=>x!==p&&x.hand.length);if(other&&p.hand.length){const a=p.hand[0];p.hand[0]=other.hand[0];other.hand[0]=a}}break}case 'A003':danger(-1);specialGear(p);break;case 'A005':s.shield=true;break;case 'A006':danger(-1);s.actions++;break;case 'A007':{const idx=s.discard.findIndex(x=>gear(x)&&x.power==='にげる');if(idx>=0)p.hand.push(s.discard.splice(idx,1)[0]);break}case 'A008':{if(!p.noTransfer){const other=s.players.find(x=>x!==p);if(other){other.hand.push(...p.hand.splice(0,Math.min(2,p.hand.length)))}}break}case 'A009':{const from=s.players.find(x=>x!==p&&x.hand.length);if(from)p.hand.push(from.hand.shift());break}case 'A010':danger(-1);draw(p);break}}
}
function specialGear(p){let temp=[],match=null;for(let i=0,n=s.deck.length;i<n;i++){const c=takeTop();if(!c)break;if(gear(c)){match=c;break}temp.push(c)}s.deck.push(...temp);if(match)addTo(p,match)}
function sealIfReady(){if(POWERS.every(power=>s.slots[power])){s.discard.push(...Object.values(s.slots));s.slots={};s.sealCount++;log('封災成功！ '+s.monsters[s.monster].name);if(s.monster===3){s.phase='won';log('4体完全封災！');return}s.monster++;s.danger=1;for(const p of s.players){while(p.hand.length>3)s.discard.push(p.hand.pop())}log('次のモンスター：'+s.monsters[s.monster].name)}}
function chooseCard(id){if(s?.phase!=='playing'||s.turn!==0||pending)return;const p=s.players[0],c=p.hand.find(x=>x.id===id);if(!c)return;selected=id;render()}
function act(){if(!s||s.turn!==0||s.actions<=0||pending)return;const p=s.players[0],c=p.hand.find(x=>x.id===selected);if(!c)return;let ok=true;if(gear(c))ok=gearPlay(p,c);else if(c.kind==='action')actionPlay(p,c);else ok=false;if(!ok){log('このカードは今は使えません');render();return}s.actions--;selected=null;sealIfReady();if(s.actions<=0)end();else render()}
function trim(p){while(p.hand.length>5){let idx=p.hand.findIndex(c=>c.kind==='action');if(idx<0)idx=p.hand.length-1;s.discard.push(p.hand.splice(idx,1)[0])}}
function end(){if(!s||s.phase!=='playing')return;trim(s.players[s.turn]);s.players[s.turn].noGear=false;s.players[s.turn].noTransfer=false;s.turns++;if(s.turns%s.players.length===0)danger(1);if(s.phase==='playing'){s.turn=(s.turn+1)%s.players.length;s.drawn=false;selected=null;turnStart()}else render()}
function cpuTurn(){let limit=0;while(s.phase==='playing'&&s.players[s.turn]?.cpu&&limit++<40){const p=s.players[s.turn];if(p.guardian&&!p.guardian.used&&p.guardian.card.id==='G007'&&s.danger>=5){p.guardian.used=true;s.shield=true;log(p.name+'がぬくもりガードを準備')}const choices=p.hand.filter(c=>gear(c)&&!s.slots[c.power]&&!p.noGear);let c=choices[0]||p.hand.find(c=>c.kind==='action');if(c){if(gear(c))gearPlay(p,c);else actionPlay(p,c)}else log(p.name+'は相談して待機');sealIfReady();end()}if(limit===40)log('CPU処理を安全停止');render()}
function resolveGuardian(exchange){if(!pending)return;const p=s.players[0];if(exchange){s.discard.push(p.guardian.card);p.guardian={card:pending.card,used:false};log('相棒を交換しました')}else{s.discard.push(pending.card);log('相棒はそのまま')}pending=null;render()}
function render(){if(!s)return;$('setup').hidden=true;$('game').hidden=false;const p=s.players[0];$('boss').textContent=s.monsters[s.monster].name;$('status').textContent=s.phase==='playing'?'封災 '+s.sealCount+'/4　危険度 '+s.danger+'/6':s.phase==='won'?'完全封災！':'ゲームオーバー';$('gauge').style.width=Math.max(0,Math.min(100,s.danger/6*100))+'%';$('slots').innerHTML=POWERS.map(power=>'<div class="slot '+(s.slots[power]?'active':'')+'">'+power+'<b>'+(s.slots[power]?.name||'◇')+'</b></div>').join('');$('team').innerHTML=s.players.map((a,i)=>'<div class="teammate">'+(i===s.turn?'▶ ':'')+a.name+'：'+a.hand.length+'枚｜'+a.guardian?.card.name+(a.guardian?.used?'（使用済）':'')+'</div>').join('');$('hand').innerHTML=p.hand.map(c=>'<button class="handcard '+(selected===c.id?'selected':'')+'" data-id="'+c.id+'"><small>'+({gear:'マモリギア',action:'アクション'}[c.kind]||c.kind)+'</small><strong>'+c.name+'</strong><small>'+c.power+'</small></button>').join('');$('info').textContent=p.hand.find(x=>x.id===selected)?.effect||'カードを選ぶと説明が表示されます。';$('log').textContent=s.log.join('\n');$('use').disabled=s.turn!==0||!selected||s.actions<=0||!!pending||s.phase!=='playing';$('pass').disabled=s.turn!==0||!!pending||s.phase!=='playing';$('prompt').hidden=!pending;if(pending)$('promptText').textContent='「'+pending.card.name+'」へ相棒を交換しますか？';$('hand').querySelectorAll('button').forEach(b=>b.onclick=()=>chooseCard(b.dataset.id));}
$('new').onclick=setup;$('use').onclick=act;$('pass').onclick=()=>{if(s?.turn===0)end()};$('yes').onclick=()=>resolveGuardian(true);$('no').onclick=()=>resolveGuardian(false);
